[project]
name = "unite"
description = "Uniform NIRSpec Inference (Turbo) Engine"
authors = [{name = "Raphael Erik Hviding", email = "raphael.hviding@gmail.com"}]
requires-python = ">= 3.12"
version = "0.0.1"
dependencies = [ 
"numpyro>=0.18.0,<0.19", 
"astropy>=7.0.1,<8", 
"matplotlib>=3.10.3,<4", 
"jaxns>=2.6.6,<3", 
# added these while developing
"pyneb>=1.1.28,<2",
"splinex @ git+https://github.com/cornelius-braun/splinex.git", "chex>=0.1.90,<0.2", 
"dotfit @ git+https://github.com/ivolabbe/dotfit.git"
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Astronomy",
  "Topic :: Scientific/Engineering :: Physics",
  "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13"
]

# [project.optional-dependencies]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["unite"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64"]

[tool.pixi.environments]
default = {features = ["default-jax"], solve-group = "default"}
mac = {features = ["mac"], solve-group = "mac"}
build = {features = ["build"], solve-group = "build"}

[tool.pixi.feature.default-jax.pypi-dependencies]
jax = ">=0.4.38,<0.6"
jaxlib = ">=0.4.38,<0.6"

[tool.pixi.feature.mac.target.osx-arm64.pypi-dependencies]
jax = "==0.5.0"
jaxlib = "==0.5.0"
jax-metal = ">=0.1.1,<0.2"

[tool.pixi.feature.build]
dependencies = { twine = ">=6.1.0,<7" }
pypi-dependencies = { build = ">=1.2.2.post1, <2" }
tasks = { build = "python -m build" }

[tool.pixi.tasks]
format = "ruff format unite"

[tool.pixi.dependencies]
python = ">=3.13.3,<3.14"
ruff = ">=0.11.9,<0.12"
pandas = ">=2.3.3,<3"
ipykernel = ">=7.1.0,<8"
setuptools = ">=80.9.0,<81"
ipywidgets = ">=8.1.8,<9"
pytest = ">=9.0.2,<10"

[tool.pixi.pypi-dependencies]
unite = { path = ".", editable = true }

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true

[tool.hatch.metadata]
allow-direct-references = true

[tool.black]
skip-magic-trailing-comma = true
